package orwashere.speedment.dao.sampledb;

import com.speedment.internal.core.runtime.ApplicationMetadata;
import javax.annotation.Generated;

/**
 * A {@link com.speedment.internal.core.runtime.ApplicationMetadata} class
 * for the {@link com.speedment.config.Project} named sampledb. This class
 * contains the meta data present at code generation time.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public class SampledbApplicationMetadata implements ApplicationMetadata {
    
    private final static StringBuilder METADATA = new StringBuilder();
    
    static {
        METADATA.append("import com.speedment.config.parameters.*\n");
        METADATA.append("\n");
        METADATA.append("name = \"sampledb\";\n");
        METADATA.append("packageLocation = \"src/main/java/\";\n");
        METADATA.append("packageName = \"orwashere.speedment.dao\";\n");
        METADATA.append("enabled = true;\n");
        METADATA.append("dbms {\n");
        METADATA.append("    ipAddress = \"localhost\";\n");
        METADATA.append("    name = \"sampledb\";\n");
        METADATA.append("    port = 3306;\n");
        METADATA.append("    typeName = \"MySQL\";\n");
        METADATA.append("    username = \"root\";\n");
        METADATA.append("    enabled = true;\n");
        METADATA.append("    schema {\n");
        METADATA.append("        columnCompressionType = ColumnCompressionType.NONE;\n");
        METADATA.append("        fieldStorageType = FieldStorageType.WRAPPER;\n");
        METADATA.append("        name = \"sampledb\";\n");
        METADATA.append("        schemaName = \"sampledb\";\n");
        METADATA.append("        storageEngineType = StorageEngineType.ON_HEAP;\n");
        METADATA.append("        defaultSchema = false;\n");
        METADATA.append("        enabled = true;\n");
        METADATA.append("        table {\n");
        METADATA.append("            columnCompressionType = ColumnCompressionType.INHERIT;\n");
        METADATA.append("            fieldStorageType = FieldStorageType.INHERIT;\n");
        METADATA.append("            name = \"contacts\";\n");
        METADATA.append("            storageEngineType = StorageEngineType.INHERIT;\n");
        METADATA.append("            tableName = \"contacts\";\n");
        METADATA.append("            enabled = true;\n");
        METADATA.append("            column {\n");
        METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
        METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
        METADATA.append("                name = \"id\";\n");
        METADATA.append("                typeMapper = com.speedment.internal.core.config.mapper.identity.IntegerIdentityMapper.class;\n");
        METADATA.append("                autoincrement = true;\n");
        METADATA.append("                enabled = true;\n");
        METADATA.append("                nullable = false;\n");
        METADATA.append("            }\n");
        METADATA.append("            column {\n");
        METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
        METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
        METADATA.append("                name = \"firstname\";\n");
        METADATA.append("                typeMapper = com.speedment.internal.core.config.mapper.identity.StringIdentityMapper.class;\n");
        METADATA.append("                autoincrement = false;\n");
        METADATA.append("                enabled = true;\n");
        METADATA.append("                nullable = true;\n");
        METADATA.append("            }\n");
        METADATA.append("            column {\n");
        METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
        METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
        METADATA.append("                name = \"lastname\";\n");
        METADATA.append("                typeMapper = com.speedment.internal.core.config.mapper.identity.StringIdentityMapper.class;\n");
        METADATA.append("                autoincrement = false;\n");
        METADATA.append("                enabled = true;\n");
        METADATA.append("                nullable = true;\n");
        METADATA.append("            }\n");
        METADATA.append("            column {\n");
        METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
        METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
        METADATA.append("                name = \"telephone\";\n");
        METADATA.append("                typeMapper = com.speedment.internal.core.config.mapper.identity.StringIdentityMapper.class;\n");
        METADATA.append("                autoincrement = false;\n");
        METADATA.append("                enabled = true;\n");
        METADATA.append("                nullable = true;\n");
        METADATA.append("            }\n");
        METADATA.append("            column {\n");
        METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
        METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
        METADATA.append("                name = \"email\";\n");
        METADATA.append("                typeMapper = com.speedment.internal.core.config.mapper.identity.StringIdentityMapper.class;\n");
        METADATA.append("                autoincrement = false;\n");
        METADATA.append("                enabled = true;\n");
        METADATA.append("                nullable = true;\n");
        METADATA.append("            }\n");
        METADATA.append("            column {\n");
        METADATA.append("                columnCompressionType = ColumnCompressionType.INHERIT;\n");
        METADATA.append("                fieldStorageType = FieldStorageType.INHERIT;\n");
        METADATA.append("                name = \"created\";\n");
        METADATA.append("                typeMapper = com.speedment.internal.core.config.mapper.identity.TimestampIdentityMapper.class;\n");
        METADATA.append("                autoincrement = false;\n");
        METADATA.append("                enabled = true;\n");
        METADATA.append("                nullable = false;\n");
        METADATA.append("            }\n");
        METADATA.append("            primaryKeyColumn {\n");
        METADATA.append("                name = \"id\";\n");
        METADATA.append("                enabled = true;\n");
        METADATA.append("            }\n");
        METADATA.append("            index {\n");
        METADATA.append("                name = \"PRIMARY\";\n");
        METADATA.append("                enabled = true;\n");
        METADATA.append("                unique = true;\n");
        METADATA.append("                indexColumn {\n");
        METADATA.append("                    name = \"id\";\n");
        METADATA.append("                    orderType = OrderType.ASC;\n");
        METADATA.append("                    enabled = true;\n");
        METADATA.append("                }\n");
        METADATA.append("            }\n");
        METADATA.append("        }\n");
        METADATA.append("    }\n");
        METADATA.append("}\n");
    }
    
    @Override
    public String getMetadata() {
        return METADATA.toString();
    }
}