package orwashere.speedment.dao.sampledb;

import com.speedment.internal.core.runtime.SpeedmentApplicationLifecycle;

import javax.annotation.Generated;

/**
 * A {@link
 * com.speedment.internal.core.runtime.SpeedmentApplicationLifecycle} class
 * for the {@link com.speedment.config.Project} named sampledb.
 * <p>
 * This Class or Interface has been automatically generated by Speedment. Any
 * changes made to this Class or Interface will be overwritten.
 * 
 * @author Speedment
 */
@Generated("Speedment")
public class SampledbApplication extends SpeedmentApplicationLifecycle<SampledbApplication> {
    
    public SampledbApplication() {
        setSpeedmentApplicationMetadata(new SampledbApplicationMetadata());
    }
    
    @Override
    protected void onInit() {
        loadAndSetProject();
        put(new orwashere.speedment.dao.sampledb.sampledb.sampledb.contacts.impl.ContactsManagerImpl(speedment));
        super.onInit();
    }
}